name: Run Python App

on:
  push:
    branches:
      - main # Or the branch you want to trigger the workflow on
  # Alternatively, for scheduled runs:
  # schedule:
  #   - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest # Or another runner environment

    steps:
      - uses: actions/checkout@v4 # Checks out your repository code
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your desired Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # If you have a requirements.txt file
          python -m pip install pymysql
      - name: Run app.py
        run: python app.py